version: '3'
services:
  device:
    build:
      context: ./app/device  # Путь к директории с кодом устройства
      dockerfile: device/dockerfile_device
    image: device
    container_name: device
    environment:
      - GATEWAY_HOST=gateway
      - GATEWAY_PORT=80
      - DEVICE_NAME=pupa_lamp
      - DEVICE_TYPE=lamp
    ports:
      - 9999:80

  gateway:
    build:
      context: ./app/gateway  # Путь к директории с кодом шлюза
      dockerfile: gateway/dockerfile_gateway
    image: gateway
    container_name: gateway
    environment:
      - HOME_ASSISTANT_HOST=home_assistant
      - HOME_ASSISTANT_PORT=8080
      - GATEWAY_PORT=80
    ports:
      - 9998:80

  home_assistant:
    build:
      context: ./app/home_assistant  # Путь к директории с кодом Home Assistant
      dockerfile: home_assistant/dockerfile_home_assistant
    image: home_assistant
    container_name: home_assistant
    ports:
      - 9997:8080


