# Используйте базовый образ Python
FROM python:3.9

# Установите зависимости из requirements.txt
COPY requirements.txt /app/requirements.txt
RUN pip install -r /app/requirements.txt

# Копируйте код в контейнер
COPY device.py /app

#ENV GATEWAY_HOST="gateway"
#ENV GATEWAY_PORT="80"
#ENV DEVICE_NAME="sensor"
#ENV FLASK_ENV=production
# Установите рабочую директорию
WORKDIR /app
# Запустите ваш код (например, с помощью команды python app.py)
CMD ["python", "device.py"]
