version: '3'
services:
  device:
    build:
      context: ./app/device
      dockerfile: dockerfile_device
    image: device
    container_name: device
    environment:
      - GATEWAY_HOST=gateway
      - GATEWAY_PORT=80
      - DEVICE_NAME=pupa_lamp
      - DEVICE_TYPE=lamp
    ports:
      - 9999:80
  device2:
    build:
      context: ./app/device
      dockerfile: dockerfile_device
    image: device
    container_name: device2
    environment:
      - GATEWAY_HOST=gateway
      - GATEWAY_PORT=80
      - DEVICE_NAME=pupa_switch
      - DEVICE_TYPE=switch
    ports:
      - 10000:80
  device3:
    build:
      context: ./app/device
      dockerfile: dockerfile_device
    image: device
    container_name: device3
    environment:
      - GATEWAY_HOST=gateway
      - GATEWAY_PORT=80
      - DEVICE_NAME=pupa_humidity_sensor
      - DEVICE_TYPE=humidity_sensor
    ports:
      - 10001:80

  gateway:
    build:
      context: ./app/gateway
      dockerfile: dockerfile_gateway
    image: gateway
    container_name: gateway
    environment:
      - HOME_ASSISTANT_HOST=home_assistant
      - HOME_ASSISTANT_PORT=8080
      - GATEWAY_PORT=80
    ports:
      - 9998:80

  home_assistant:
    build:
      context: ./app/home_assistant
      dockerfile: dockerfile_home_assistant
    image: home_assistant
    container_name: home_assistant
    ports:
      - 9997:8080
    restart: always

