# Используйте базовый образ Python
FROM python:3.9
COPY requirements_mqtt.txt /app/requirements.txt
RUN pip install --upgrade pip
RUN pip install -r /app/requirements.txt
COPY home_ass_mqtt.py /app
WORKDIR /app
CMD ["python", "home_ass_mqtt.py"]
